// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgz_brhziRdkxtbcMvtbAepLAk5rdgvFI',
    appId: '1:151261216391:web:62921d1b8cb506cf364222',
    messagingSenderId: '151261216391',
    projectId: 'doclink-5b041',
    authDomain: 'doclink-5b041.firebaseapp.com',
    storageBucket: 'doclink-5b041.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCQYkeUtWv_2jo-B16_3PnhAJZ5lschzA',
    appId: '1:151261216391:android:da634583fd4eb7a5364222',
    messagingSenderId: '151261216391',
    projectId: 'doclink-5b041',
    storageBucket: 'doclink-5b041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy7Ysa7mXwJntoB702JUc5VjcHvlr6gjk',
    appId: '1:151261216391:ios:38909b4257b942e0364222',
    messagingSenderId: '151261216391',
    projectId: 'doclink-5b041',
    storageBucket: 'doclink-5b041.appspot.com',
    iosClientId: '151261216391-7odaupo2chh5ustmh6fh3a8dlqf0jae0.apps.googleusercontent.com',
    iosBundleId: 'com.example.docLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy7Ysa7mXwJntoB702JUc5VjcHvlr6gjk',
    appId: '1:151261216391:ios:38909b4257b942e0364222',
    messagingSenderId: '151261216391',
    projectId: 'doclink-5b041',
    storageBucket: 'doclink-5b041.appspot.com',
    iosClientId: '151261216391-7odaupo2chh5ustmh6fh3a8dlqf0jae0.apps.googleusercontent.com',
    iosBundleId: 'com.example.docLink',
  );
}
